branches:
  except:
    - gh-pages
sudo: false
language: perl
matrix:
    include:
        - perl: "5.24"
        - perl: "5.22"
        - perl: "5.20"
          dist: trusty
        - perl: "5.18"
          dist: trusty
        - perl: "5.16"
          dist: trusty
        - perl: "5.14"
          dist: trusty

script: "perl Makefile.PL && make && make test"
